In [27]:
import numpy as np

In [28]:
def gaussian(A):
    # приводим матрицу к треугольному виду
    # i - опорная строка
    # j - текущая строка (всегда меньше i)
    for i in range(len(A)):
        for j in range(i + 1, len(A)):
            A[j] -= A[i] * A[j][i] / A[i][i]

    print(A)

    # обратный ход
    x = np.array([0] * len(A), dtype=float) # вектор решений

    i = len(A) - 1
    while i >= 0:
        x[i] = (A[i][-1] - sum(x * A[i][0:-1])) / A[i][i]
        i -= 1

    return x

In [29]:
A_list = [
    [
        [7, 2, 3, 15],
        [5, -3, 2, 15],
        [10, -11, 5, 36],
    ],
    [
        [3, 5, 1, 165],
        [4, 1, 4, 136],
        [6, 4, 2, 210],
    ]
]

In [30]:
for i in range(len(A_list)):
    print('Матрица:')
    for row in A_list[i]:
        print(row)

    print('\nРешение методом Гаусса:')
    print(gaussian(np.array(A_list[i], dtype=float)), '\n')

Матрица:
[7, 2, 3, 15]
[5, -3, 2, 15]
[10, -11, 5, 36]

Решение методом Гаусса:
[[ 7.          2.          3.         15.        ]
 [ 0.         -4.42857143 -0.14285714  4.28571429]
 [ 0.          0.          1.16129032  1.16129032]]
[ 2. -1.  1.] 

Матрица:
[3, 5, 1, 165]
[4, 1, 4, 136]
[6, 4, 2, 210]

Решение методом Гаусса:
[[  3.           5.           1.         165.        ]
 [  0.          -5.66666667   2.66666667 -84.        ]
 [  0.           0.          -2.82352941 -31.05882353]]
[18. 20. 11.] 



In [32]:
def gauss(a):
    turns = len(a)

    # прямой ход
    for turn in range(turns):  # опорная строка
        for i in range(turn + 1, turns):  # текущая строка (всегда меньше turn)
            temp = a[i][turn]
            for j in range(len(a[1])):
                a[i][j] -= a[turn][j] * temp / a[turn][turn]

    x = [0] * turns

    # обратный ход
    for turn in reversed(range(turns)): # 2, 1, 0

        *split, res = a[turn][turn:]

        sum = 0
        for i, k in enumerate(reversed(split)):
            sum += k * x[turns-i-1]

        x[turn] = (res - sum) / a[turn][turn]

    return x


In [33]:
for i in range(len(A_list)):
    print('Матрица:')
    for row in A_list[i]:
        print(row)

    print('\nРешение методом Гаусса:')
    print(gauss(A_list[i]), '\n')

Матрица:
[7, 2, 3, 15]
[5, -3, 2, 15]
[10, -11, 5, 36]

Решение методом Гаусса:
[2.0000000000000004, -1.0, 0.9999999999999992] 

Матрица:
[3, 5, 1, 165]
[4, 1, 4, 136]
[6, 4, 2, 210]

Решение методом Гаусса:
[18.0, 20.0, 11.000000000000002] 

